version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/cli"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
