package webpush

import (
	"context"
	"encoding/base64"
	"os"
	"strings"
	"testing"
)

// Valid test keys generated by webpush-go (P-256 EC, base64url-encoded).
const (
	testPublicKey  = "BIJDQwsuHlUBI50e_u55UmLEaCFQCgUhOotDK3-JEWq6jaVEHtGNI8HTF0OrZstOlldSjc0-a_beRXz6WKCw7XA"
	testPrivateKey = "4tzdsuB8MYZ6-Gw9uCLQirCvL9dTq6TdxyQvMxz9sKE"
)

// setEnvForTest sets multiple env vars for the duration of a test and restores
// their previous values (or unsets them) when the test completes.
func setEnvForTest(t *testing.T, vars map[string]string) {
	t.Helper()
	originals := make(map[string]*string, len(vars))
	for k := range vars {
		if v, ok := os.LookupEnv(k); ok {
			v := v
			originals[k] = &v
		} else {
			originals[k] = nil
		}
	}
	t.Cleanup(func() {
		for k, orig := range originals {
			if orig == nil {
				os.Unsetenv(k)
			} else {
				os.Setenv(k, *orig)
			}
		}
	})
	for k, v := range vars {
		os.Setenv(k, v)
	}
}

func TestInitVAPIDKeys_EnvVarsUsedInBothModes(t *testing.T) {
	setEnvForTest(t, map[string]string{
		"VAPID_PUBLIC_KEY":  testPublicKey,
		"VAPID_PRIVATE_KEY": testPrivateKey,
	})

	// Production mode
	keys, err := InitVAPIDKeys(context.Background(), nil, false)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if keys == nil {
		t.Fatal("expected keys, got nil")
	}
	if keys.PublicKey != testPublicKey {
		t.Errorf("expected public key %q, got %q", testPublicKey, keys.PublicKey)
	}
	if keys.PrivateKey != testPrivateKey {
		t.Errorf("expected private key %q, got %q", testPrivateKey, keys.PrivateKey)
	}

	// Dev mode
	keys, err = InitVAPIDKeys(context.Background(), nil, true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if keys == nil {
		t.Fatal("expected keys, got nil")
	}
	if keys.PublicKey != testPublicKey {
		t.Errorf("expected public key %q, got %q", testPublicKey, keys.PublicKey)
	}
}

func TestInitVAPIDKeys_ProductionDisabledWithoutEnvVars(t *testing.T) {
	// When no VAPID vars are set, Web Push is simply disabled (nil, nil).
	setEnvForTest(t, map[string]string{
		"VAPID_PUBLIC_KEY":  "",
		"VAPID_PRIVATE_KEY": "",
	})

	keys, err := InitVAPIDKeys(context.Background(), nil, false)
	if err != nil {
		t.Fatalf("expected no error (Web Push disabled), got: %v", err)
	}
	if keys != nil {
		t.Error("expected nil keys when Web Push is disabled")
	}
}

func TestInitVAPIDKeys_ProductionErrorsOnPartialConfig(t *testing.T) {
	// Only public key set — this is a misconfiguration, should error.
	setEnvForTest(t, map[string]string{
		"VAPID_PUBLIC_KEY":  testPublicKey,
		"VAPID_PRIVATE_KEY": "",
	})

	_, err := InitVAPIDKeys(context.Background(), nil, false)
	if err == nil {
		t.Fatal("expected error when only VAPID_PUBLIC_KEY is set in production")
	}
	if !strings.Contains(err.Error(), "VAPID_PRIVATE_KEY") {
		t.Errorf("expected error to mention VAPID_PRIVATE_KEY, got: %v", err)
	}

	// Only private key set.
	setEnvForTest(t, map[string]string{
		"VAPID_PUBLIC_KEY":  "",
		"VAPID_PRIVATE_KEY": testPrivateKey,
	})

	_, err = InitVAPIDKeys(context.Background(), nil, false)
	if err == nil {
		t.Fatal("expected error when only VAPID_PRIVATE_KEY is set in production")
	}
	if !strings.Contains(err.Error(), "VAPID_PUBLIC_KEY") {
		t.Errorf("expected error to mention VAPID_PUBLIC_KEY, got: %v", err)
	}
}

func TestInitVAPIDKeys_DevModeReturnsNilWithoutDBOrEnvVars(t *testing.T) {
	setEnvForTest(t, map[string]string{
		"VAPID_PUBLIC_KEY":  "",
		"VAPID_PRIVATE_KEY": "",
	})

	keys, err := InitVAPIDKeys(context.Background(), nil, true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if keys != nil {
		t.Error("expected nil keys in dev mode without DB or env vars")
	}
}

func TestInitVAPIDKeys_PartialEnvVarsFallThrough(t *testing.T) {
	// Only public key set — should not use env vars (need both).
	setEnvForTest(t, map[string]string{
		"VAPID_PUBLIC_KEY":  testPublicKey,
		"VAPID_PRIVATE_KEY": "",
	})

	// In production mode, this should error since env vars are incomplete
	// and auto-generation is not allowed.
	_, err := InitVAPIDKeys(context.Background(), nil, false)
	if err == nil {
		t.Fatal("expected error in production with partial VAPID env vars")
	}

	// In dev mode with no DB, should return nil (no env vars, no DB).
	keys, err := InitVAPIDKeys(context.Background(), nil, true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if keys != nil {
		t.Error("expected nil keys in dev mode with partial env vars and no DB")
	}
}

func TestInitVAPIDKeys_InvalidBase64URLRejected(t *testing.T) {
	setEnvForTest(t, map[string]string{
		"VAPID_PUBLIC_KEY":  "not-valid-base64!!!",
		"VAPID_PRIVATE_KEY": testPrivateKey,
	})

	_, err := InitVAPIDKeys(context.Background(), nil, false)
	if err == nil {
		t.Fatal("expected error for invalid base64url public key")
	}
	if !strings.Contains(err.Error(), "VAPID_PUBLIC_KEY") {
		t.Errorf("expected error to mention VAPID_PUBLIC_KEY, got: %v", err)
	}
}

func TestInitVAPIDKeys_TruncatedKeyRejected(t *testing.T) {
	// Valid base64url but too short for a P-256 public key (~87 chars expected).
	setEnvForTest(t, map[string]string{
		"VAPID_PUBLIC_KEY":  "BIJDQwsuHlUBI50e",
		"VAPID_PRIVATE_KEY": testPrivateKey,
	})

	_, err := InitVAPIDKeys(context.Background(), nil, false)
	if err == nil {
		t.Fatal("expected error for truncated public key")
	}
	if !strings.Contains(err.Error(), "bytes") {
		t.Errorf("expected error to mention bytes, got: %v", err)
	}
}

func TestInitVAPIDKeys_WhitespaceTrimmingInEnvVars(t *testing.T) {
	// Keys with trailing whitespace (common copy-paste issue).
	setEnvForTest(t, map[string]string{
		"VAPID_PUBLIC_KEY":  testPublicKey + "\n",
		"VAPID_PRIVATE_KEY": "  " + testPrivateKey + "  ",
	})

	keys, err := InitVAPIDKeys(context.Background(), nil, false)
	if err != nil {
		t.Fatalf("expected whitespace to be trimmed, got error: %v", err)
	}
	if keys == nil {
		t.Fatal("expected keys, got nil")
	}
	if keys.PublicKey != testPublicKey {
		t.Errorf("expected trimmed public key %q, got %q", testPublicKey, keys.PublicKey)
	}
	if keys.PrivateKey != testPrivateKey {
		t.Errorf("expected trimmed private key %q, got %q", testPrivateKey, keys.PrivateKey)
	}
}

func TestPublicKeyFingerprint(t *testing.T) {
	keys := &VAPIDKeys{PublicKey: testPublicKey, PrivateKey: testPrivateKey}
	fp := keys.PublicKeyFingerprint()
	if len(fp) != 8 { // 4 bytes = 8 hex chars
		t.Errorf("expected 8-char hex fingerprint, got %q (%d chars)", fp, len(fp))
	}

	// Same key should produce the same fingerprint.
	fp2 := keys.PublicKeyFingerprint()
	if fp != fp2 {
		t.Errorf("fingerprint not deterministic: %q != %q", fp, fp2)
	}
}

func TestValidateVAPIDKeyFormat(t *testing.T) {
	// Valid keys
	if err := validateVAPIDKeyFormat(testPublicKey, testPrivateKey); err != nil {
		t.Errorf("expected valid keys to pass, got: %v", err)
	}

	// Invalid base64url
	if err := validateVAPIDKeyFormat("!!!invalid!!!", testPrivateKey); err == nil {
		t.Error("expected error for invalid base64url public key")
	}
	if err := validateVAPIDKeyFormat(testPublicKey, "!!!invalid!!!"); err == nil {
		t.Error("expected error for invalid base64url private key")
	}

	// Wrong decoded byte length (valid base64url but not 65/32 bytes)
	if err := validateVAPIDKeyFormat("BIJDQwsuHlUBI50e", testPrivateKey); err == nil {
		t.Error("expected error for wrong-length public key")
	}
	if err := validateVAPIDKeyFormat(testPublicKey, "BIJDQ"); err == nil {
		t.Error("expected error for wrong-length private key")
	}

	// Correct length (65 bytes) but wrong prefix byte (0x05 instead of 0x04).
	badPrefix := make([]byte, 65)
	badPrefix[0] = 0x05 // invalid prefix
	badPrefixKey := base64.RawURLEncoding.EncodeToString(badPrefix)
	if err := validateVAPIDKeyFormat(badPrefixKey, testPrivateKey); err == nil {
		t.Error("expected error for public key with wrong prefix byte")
	} else if !strings.Contains(err.Error(), "prefix byte") {
		t.Errorf("expected error about prefix byte, got: %v", err)
	}

	// Padded base64url keys should also be accepted.
	paddedPub := base64.URLEncoding.EncodeToString(mustDecodeRaw(t, testPublicKey))
	paddedPriv := base64.URLEncoding.EncodeToString(mustDecodeRaw(t, testPrivateKey))
	if err := validateVAPIDKeyFormat(paddedPub, paddedPriv); err != nil {
		t.Errorf("expected padded base64url keys to pass, got: %v", err)
	}
}

// mustDecodeRaw decodes a raw (unpadded) base64url string, failing the test on error.
func mustDecodeRaw(t *testing.T, s string) []byte {
	t.Helper()
	b, err := base64.RawURLEncoding.DecodeString(s)
	if err != nil {
		t.Fatalf("failed to decode %q: %v", s, err)
	}
	return b
}
