// Package all blank-imports every built-in connector package so that their
// init() functions run and self-register with the connectors registry.
//
// Usage in main.go:
//
//	import _ "github.com/supersuit-tech/permission-slip/connectors/all"
//
// To add a new connector, create its register.go with an init() that calls
// connectors.RegisterBuiltIn(New()), then add a blank import here.
package all

import (
	_ "github.com/supersuit-tech/permission-slip/connectors/airtable"
	_ "github.com/supersuit-tech/permission-slip/connectors/amadeus"
	_ "github.com/supersuit-tech/permission-slip/connectors/asana"
	_ "github.com/supersuit-tech/permission-slip/connectors/aws"
	_ "github.com/supersuit-tech/permission-slip/connectors/bigquery"
	_ "github.com/supersuit-tech/permission-slip/connectors/calendly"
	_ "github.com/supersuit-tech/permission-slip/connectors/coinbaseagentkit"
	_ "github.com/supersuit-tech/permission-slip/connectors/confluence"
	_ "github.com/supersuit-tech/permission-slip/connectors/datadog"
	_ "github.com/supersuit-tech/permission-slip/connectors/discord"
	_ "github.com/supersuit-tech/permission-slip/connectors/docusign"
	_ "github.com/supersuit-tech/permission-slip/connectors/doordash"
	_ "github.com/supersuit-tech/permission-slip/connectors/dropbox"
	_ "github.com/supersuit-tech/permission-slip/connectors/dynamodb"
	_ "github.com/supersuit-tech/permission-slip/connectors/expedia"
	_ "github.com/supersuit-tech/permission-slip/connectors/figma"
	_ "github.com/supersuit-tech/permission-slip/connectors/firestore"
	_ "github.com/supersuit-tech/permission-slip/connectors/github"
	_ "github.com/supersuit-tech/permission-slip/connectors/google"
	_ "github.com/supersuit-tech/permission-slip/connectors/hubspot"
	_ "github.com/supersuit-tech/permission-slip/connectors/instacart"
	_ "github.com/supersuit-tech/permission-slip/connectors/intercom"
	_ "github.com/supersuit-tech/permission-slip/connectors/jira"
	_ "github.com/supersuit-tech/permission-slip/connectors/kroger"
	_ "github.com/supersuit-tech/permission-slip/connectors/linear"
	_ "github.com/supersuit-tech/permission-slip/connectors/linkedin"
	_ "github.com/supersuit-tech/permission-slip/connectors/make"
	_ "github.com/supersuit-tech/permission-slip/connectors/meta"
	_ "github.com/supersuit-tech/permission-slip/connectors/microsoft"
	_ "github.com/supersuit-tech/permission-slip/connectors/monday"
	_ "github.com/supersuit-tech/permission-slip/connectors/mongodb"
	_ "github.com/supersuit-tech/permission-slip/connectors/mysql"
	_ "github.com/supersuit-tech/permission-slip/connectors/netlify"
	_ "github.com/supersuit-tech/permission-slip/connectors/notion"
	_ "github.com/supersuit-tech/permission-slip/connectors/pagerduty"
	_ "github.com/supersuit-tech/permission-slip/connectors/paypal"
	_ "github.com/supersuit-tech/permission-slip/connectors/plaid"
	_ "github.com/supersuit-tech/permission-slip/connectors/postgres"
	_ "github.com/supersuit-tech/permission-slip/connectors/quickbooks"
	_ "github.com/supersuit-tech/permission-slip/connectors/redis"
	_ "github.com/supersuit-tech/permission-slip/connectors/salesforce"
	_ "github.com/supersuit-tech/permission-slip/connectors/sendgrid"
	_ "github.com/supersuit-tech/permission-slip/connectors/shopify"
	_ "github.com/supersuit-tech/permission-slip/connectors/slack"
	_ "github.com/supersuit-tech/permission-slip/connectors/snowflake"
	_ "github.com/supersuit-tech/permission-slip/connectors/square"
	_ "github.com/supersuit-tech/permission-slip/connectors/stripe"
	_ "github.com/supersuit-tech/permission-slip/connectors/supabase"
	_ "github.com/supersuit-tech/permission-slip/connectors/trello"
	_ "github.com/supersuit-tech/permission-slip/connectors/twilio"
	_ "github.com/supersuit-tech/permission-slip/connectors/vercel"
	_ "github.com/supersuit-tech/permission-slip/connectors/walmart"
	_ "github.com/supersuit-tech/permission-slip/connectors/x"
	_ "github.com/supersuit-tech/permission-slip/connectors/zapier"
	_ "github.com/supersuit-tech/permission-slip/connectors/zendesk"
	_ "github.com/supersuit-tech/permission-slip/connectors/zoom"

	_ "github.com/supersuit-tech/permission-slip/connectors/cloudflare"
)
