package api

// ErrorCode represents a machine-readable error code from the API spec.
type ErrorCode string

const (
	ErrInvalidRequest           ErrorCode = "invalid_request"
	ErrInvalidActionType        ErrorCode = "invalid_action_type"
	ErrUnsupportedActionType    ErrorCode = "unsupported_action_type"
	ErrUnsupportedActionVersion ErrorCode = "unsupported_action_version"
	ErrAgentIDMismatch          ErrorCode = "agent_id_mismatch"
	ErrInvalidPublicKey         ErrorCode = "invalid_public_key"
	ErrInvalidSignature         ErrorCode = "invalid_signature"
	ErrTimestampExpired         ErrorCode = "timestamp_expired"
	ErrInvalidCode              ErrorCode = "invalid_code"
	ErrInvalidToken             ErrorCode = "invalid_token"
	ErrInsufficientScope        ErrorCode = "insufficient_scope"
	ErrAgentNotAuthorized       ErrorCode = "agent_not_authorized"
	ErrApprovalDenied           ErrorCode = "approval_denied"
	ErrTokenAlreadyUsed         ErrorCode = "token_already_used"
	ErrInvalidParameters        ErrorCode = "invalid_parameters"
	ErrAgentNotFound            ErrorCode = "agent_not_found"
	ErrApproverNotFound         ErrorCode = "approver_not_found"
	ErrApprovalNotFound         ErrorCode = "approval_not_found"
	ErrProfileNotFound          ErrorCode = "profile_not_found"
	ErrCredentialNotFound       ErrorCode = "credential_not_found"
	ErrConnectorNotFound        ErrorCode = "connector_not_found"
	ErrCredentialsNotFound      ErrorCode = "credentials_not_found"
	ErrNoMatchingStanding       ErrorCode = "no_matching_standing_approval"
	ErrStandingExhausted        ErrorCode = "standing_approval_exhausted"
	ErrConstraintViolation      ErrorCode = "constraint_violation"
	ErrStandingExpired          ErrorCode = "standing_approval_expired"
	ErrAgentAlreadyRegistered   ErrorCode = "agent_already_registered"
	ErrDuplicateRequestID       ErrorCode = "duplicate_request_id"
	ErrApprovalAlreadyResolved  ErrorCode = "approval_already_resolved"
	ErrDuplicateCredential      ErrorCode = "duplicate_credential"
	ErrRegistrationExpired      ErrorCode = "registration_expired"
	ErrVerificationLocked       ErrorCode = "verification_locked"
	ErrApprovalExpired          ErrorCode = "approval_expired"
	ErrRateLimited              ErrorCode = "rate_limited"
	ErrInternalError            ErrorCode = "internal_error"
	ErrUpstreamError            ErrorCode = "upstream_error"
	ErrActionConfigNotFound     ErrorCode = "action_config_not_found"
	ErrInvalidConfiguration     ErrorCode = "invalid_configuration"
	ErrConfigurationDisabled    ErrorCode = "configuration_disabled"
	ErrConfigActionTypeMismatch ErrorCode = "configuration_action_type_mismatch"
	ErrInvalidReference         ErrorCode = "invalid_reference"
	ErrServiceUnavailable       ErrorCode = "service_unavailable"
	ErrAgentLimitReached        ErrorCode = "agent_limit_reached"
	ErrStandingApprovalLimitReached ErrorCode = "standing_approval_limit_reached"
	ErrCredentialLimitReached   ErrorCode = "credential_limit_reached"
	ErrSubscriptionNotFound     ErrorCode = "subscription_not_found"
	ErrAlreadySubscribed        ErrorCode = "already_subscribed"
	ErrAlreadyDowngraded        ErrorCode = "already_downgraded"
	ErrDowngradeLimitExceeded   ErrorCode = "downgrade_limit_exceeded"
	ErrBillingNotEnabled        ErrorCode = "billing_not_enabled"
	ErrSMSRequiresPaidPlan      ErrorCode = "sms_requires_paid_plan"
)
